---
- name: Update cache
  apt: update_cache=yes
  tags:
    - deploy

- name: Add Docker repository key
  command: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  tags:
    - deploy

- name: Add Docker repository to APT
  shell: echo deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main > /etc/apt/sources.list.d/docker.list
  tags:
    - deploy

- name: Update cache
  apt: update_cache=true 
  tags:
    - deploy

- name: Install Docker 
  apt: pkg=docker-engine state=present
  tags:
    - deploy
